# Generated by Django 6.0.7 on 2026-07-23 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ecoles', '0003_alter_etudiant_id_user_alter_professeur_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Non justifié'), (1, 'Justifié')], default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='Ecoles.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(help_text='Note sur 20')),
                ('matiere_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Ecoles.matieres')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='Ecoles.etudiant')),
            ],
        ),
    ]
