# Generated by Django 6.0.7 on 2026-07-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relever_NA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user_id',
            new_name='student_id',
        ),
    ]
