# Generated by Django 6.0.7 on 2026-07-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relever_NA', '0002_rename_user_id_notes_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='student',
            new_name='student_id',
        ),
    ]
