# Generated by Django 6.0.7 on 2026-07-24 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecoles', '0003_alter_etudiant_id_user_alter_professeur_id_user'),
        ('Relever_NA', '0003_rename_student_absence_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='student_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='Ecoles.etudiant'),
        ),
    ]
