# Generated by Django 6.0.7 on 2026-07-24 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relever_NA', '0004_alter_notes_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absence',
            old_name='student_id',
            new_name='student',
        ),
    ]
