# Generated by Django 6.0.7 on 2026-08-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Relever_NA', '0005_rename_student_id_absence_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='student_id',
            new_name='matricule',
        ),
    ]
