# Generated by Django 6.1 on 2026-08-11 08:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relever_NA', '0006_rename_student_id_notes_matricule'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
