# Generated by Django 6.1 on 2026-08-11 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Relever_NA', '0007_notes_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='heure',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
