# Generated by Django 6.1 on 2026-08-17 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecoles', '0009_alter_classes_nom'),
        ('Relever_NA', '0008_absence_heure'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='matiere',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='Ecoles.matieres'),
        ),
    ]
