# Generated by Django 6.0.7 on 2026-08-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecoles', '0003_alter_etudiant_id_user_alter_professeur_id_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='status',
            field=models.IntegerField(choices=[(0, 'Non justifié'), (1, 'Justifié')], default=0),
        ),
    ]
