# Generated by Django 6.0.7 on 2026-08-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecoles', '0004_classes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='status',
            field=models.IntegerField(choices=[(0, 'AFFECTER'), (1, 'NON AFFECTER ')], default=0),
        ),
    ]
