# Generated by Django 6.0.8 on 2026-08-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecoles', '0005_alter_classes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='status',
            field=models.CharField(choices=[('COMPLET', 'Complet'), ('OUVERT', 'Ouvert'), ('SATURE', 'Saturé')], default='OUVERT', max_length=20),
        ),
    ]
