# Generated by Django 6.0.8 on 2026-08-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecoles', '0006_alter_classes_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='status',
        ),
    ]
