# Generated by Django 6.0.8 on 2026-08-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecoles', '0007_remove_classes_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='code_classe',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
