# Generated by Django 6.0.8 on 2026-08-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecoles', '0008_classes_code_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='nom',
            field=models.CharField(max_length=40),
        ),
    ]
