# Generated by Django 6.1 on 2026-08-18 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecoles', '0009_alter_classes_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professeur',
            name='matiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecoles.matieres'),
        ),
    ]
