# Generated by Django 6.0.7 on 2026-07-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
