# Generated by Django 6.0.7 on 2026-07-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profils', '0003_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'administrateur'), ('professeur', 'professeur'), ('etudiant', 'etudiant')], default='etudiant', max_length=40),
        ),
    ]
